spring.application.name=isoValidator
server.port=8082

server.port=${PORT:8082}

spring.datasource.url=jdbc:postgresql://localhost:5432/uberapp
spring.datasource.username=rishijha
spring.datasource.password=rishijha


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
