spring.application.name=isoValidator
server.port=8082

server.port=${PORT:8082}

spring.datasource.url=jdbc:postgresql://localhost:5432/MyProjectDB
spring.datasource.username=rishijha
spring.datasource.password=rishijha


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


JWT_SECRET=9f8B2kL5mX1vP7qR4tW0yZ3cA6eH8jN2
JWT_EXPIRATION_MS=3600000

BOOTSTRAP_ADMIN_USERNAME=Rishi
BOOTSTRAP_ADMIN_PASSWORD=Rishi@123